### ISSUE TITLE
Wrong repository url

### ISSUE THREAD

**Issue by ichigotake** [tomorrowkey/InjectLogTagPlugin#1]
AndroidStudio の Plugin 一覧に表示されているURLが古いものになっており、リンク先へジャンプするとリポジトリが見つからない状態になっています。
- Plugin 一覧の表示URL: https://github.com/tomorrowkey/InjectLogTag
- 正しいリポジトリURL: https://github.com/tomorrowkey/InjectLogTagPlugin

![2014-12-24 19 32 01](https://cloud.githubusercontent.com/assets/381483/5547783/2275582c-8ba4-11e4-8efc-23f6187515df.png)

修正点はこちらでしょうか

https://github.com/tomorrowkey/InjectLogTagPlugin/blob/6d75a443873a4999dd636cdd946f6dd5e0f40203/InjectLogTagPlugin/META-INF/plugin.xml#L5

**Comment by tomorrowkey** [comment]
あー、ほんとだ、修正しよう

**Comment by tomorrowkey** [comment]
It has been fixed on v1.0.2
